name: Build Frontend and Backend Services

on:
  push:
    branches:
      - master

jobs:

  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend dependencies
        working-directory: apps/web
        run: npm install

      - name: Build frontend
        working-directory: apps/web
        run: npm run build


  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Resume Service
        working-directory: services/resume-service
        run: npm install

      - name: Install Analysis Service
        working-directory: services/analysis-service
        run: npm install

      - name: Install API Gateway
        working-directory: services/api-gateway
        run: npm install
